[theme]
base = "light"
primaryColor = "#0878E8"
backgroundColor = "#F2F7FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102B53"
linkColor = "#0878E8"
borderColor = "#DCE8F5"
dataframeBorderColor = "#DCE8F5"
dataframeHeaderBackgroundColor = "#E8F3FF"
baseRadius = "medium"
buttonRadius = "medium"

[theme.sidebar]
backgroundColor = "#08264F"
secondaryBackgroundColor = "#103866"
textColor = "#F5F9FF"
primaryColor = "#45A4FF"
borderColor = "#29466A"
